### PR TITLE
Also generate resource information for api tester

### PR DESCRIPTION
**Pull request by epelz**

### CODE REVIEW

**Comment by epelz** [comment]
Looks like the github api token didn't have permission to push to asana-api-json. Are you able to update the token? https://travis-ci.org/Asana/asana-api-meta/builds/51452755

**Comment by slobak** [comment]
I did regen the token but am not going to add it back until we fix the
security problem.

For now you can actually run the deploy manually I think, from your repo?
`gulp deploy json` is probably all you need to do, assuming you've got your
git environment already set up.

**Comment by epelz** [comment]
Just merged your changes in, and it successfully pushed changes to the json repository and npm! I think this is good to go then.

**Comment by epelz** [comment]
This should be all set now!

**Pull request merged**
